apiVersion: v1
kind: Service
metadata:
  name: ${payments_hashicups_service_name}
  namespace: ${frontend_namespace}
  labels:
    app: ${payments_hashicups_service_name}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 1800
      targetPort: 8080
  selector:
    app: ${payments_hashicups_service_name}
