apiVersion: v1
kind: Service
metadata:
  name: ${public_api_hashicups_service_name}
  namespace: ${frontend_namespace}
  labels:
    app: ${public_api_hashicups_service_name}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ${public_api_hashicups_service_name}
