apiVersion: v1
kind: Service
metadata:
  name: ${frontend_hashicups_service_name}
  namespace: ${frontend_namespace}
  labels:
    app: ${frontend_hashicups_service_name}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: ${frontend_hashicups_service_name}
