apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: ${frontend_namespace}
data:
  config: |
    {
      "db_connection": "${db_connection}",
      "bind_address": ":9090",
      "metrics_address": ":9103"
    }
