apiVersion: v1
kind: Service
metadata:
  name: ${product_api_hashicups_service_name}
  namespace: ${frontend_namespace}
spec:
  selector:
    app: ${product_api_hashicups_service_name}
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
