apiVersion: v1
kind: Service
metadata:
  name: ${frontend_service_name}
  namespace: ${frontend_namespace}
  labels:
    app: ${frontend_service_name}
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: ${frontend_service_name}
