apiVersion: v1
kind: Service
metadata:
  name: ${backend_service_name}
  namespace: ${backend_namespace}
  labels:
    app: ${backend_service_name}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: ${backend_service_name}
